apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-microservice
  namespace: mircroservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: devops
        image: Carlos6019/devops-microservice:latest
        ports:
        - containerPort: 5000

