name: microservice

on:
  push:
    branches:
      - production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Build Docker image
      run: |
        docker build -t <tu_imagen_docker> .

    - name: Push Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker push <tu_imagen_docker>

    - name: Deploy to EKS
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }} # Almacena el contexto de EKS en los secretos
      run: |
        kubectl apply -f ../infra-repo/deployment.yaml
        kubectl apply -f ../infra-repo/service.yaml

